### PR TITLE
Bump rustler_precompiled to v0.5.2

### PR DESCRIPTION
**Pull request by Benjamin-Philip**
Rustler Precompiled had a bug in v0.5.1 wherein precompiled NIFs could not run on Fedora and RHEL machines. See
https://github.com/philss/rustler_precompiled/issues/30

This commit bumps Rustler Precompiled to v0.5.2 to eliminate this bug in html5erver.

### CODE REVIEW

**Comment by philss** [comment]
@Benjamin-Philip thanks again! Since the version requirement is relaxed, you can upgrade `rustler_precompiled` in projects using `html5ever_elixir` by running `mix deps.update rustler_precompiled`.

In any case, this change is going to force the upgrade, so it's good.

**Comment by Benjamin-Philip** [comment]
In that case I'm gonna send a PR to Floki as well.

**Comment by Benjamin-Philip** [comment]
Could you release a new patched version as well?

**Comment by philss** [comment]
> Could you release a new patched version (v0.13.2) as well?

@Benjamin-Philip sure! But I'm going to do that in the morning. Sleep time for me now :smile:

**Comment by Benjamin-Philip** [comment]
Sure! It's 9:30 am for me.

**Comment by Benjamin-Philip** [comment]
@philss, I don't mean to be rude, but ping

**Comment by philss** [comment]
@Benjamin-Philip no problem. This is released in `v0.14.0`.

**Comment by philss** [comment]
> Could you release a new patched version (v0.13.2) as well?

I forgot to say that this would be a minor, since it would break who were depending of `0.4` of `rustler_precompiled` for some reason.

**Pull request merged**
